i2271: Refactor of the montagu-machine code
vimc/montagu-machine pull request #2
Opened 2018-10-16 14:23 UTC by richfitz

This moves the provisioning code (and therefore necessarily the
Vagrantfile) to the top level of the repo, so that we can use
these scripts to provision physical machines as well as virtual.

The systemctl bits move into their own directory but remain essentially
unchanged

Some renames are simply dropping '.sh' extensions

Alternative approach, but same content, as #1

2018-10-16 14:32 UTC, richfitz commented on Vagrantfile
> +vault_config_file = 'staging/shared/vault_config'
This set of lines allows using vault during provisioning

2018-10-16 14:32 UTC, richfitz commented on Vagrantfile
> +    shell.path = 'provision/setup-docker'
The setup-docker script is a bit more flexible now - see the script for details.  We can modify instructions elsewhere to use that script for setting up physical machines

2018-10-16 14:32 UTC, richfitz commented on Vagrantfile
> +  config.vm.provision :shell do |shell|
This step was always manual previously

2018-10-16 14:32 UTC, richfitz commented on provision/setup-automatic-updates
> +cat <<EOF > /etc/apt/apt.conf.d/20auto-upgrades
This file just swaps `tee` for the more usual `cat`. This was my fault initially in not giving clear instructions

2018-10-16 14:32 UTC, richfitz commented on provision/setup-docker
> +set -ex
More flexible version of the old script

- environment variable `DOCKER_LARGE_DISK` is used to indicate where to put docker's large files (we do this on the annex and I have it this way locally)
- all other arguments are users that will be granted permission to use the docker socket

2018-10-16 14:32 UTC, richfitz commented on provision/setup-machine-metrics
> +#!/usr/bin/env bash
This seems worth testing. If we ever want to monitor these vms this way we'll need to expose the ports via the Vagrantfile but point them at different numbers...

2018-10-16 14:32 UTC, richfitz commented on provision/setup-montagu
> +#!/usr/bin/env bash
This is based off of an restore script that was never really used. But with the vault setup now included we can just go ahead and set everything up

2018-10-16 14:32 UTC, richfitz commented on provision/setup-montagu
> +    git -C ${MONTAGU_PATH} checkout i1472
This line needs removing once https://github.com/vimc/montagu/pull/80 is merged

2018-10-16 14:32 UTC, richfitz commented on provision/setup-vagrant
> +#!/usr/bin/env bash
This is designed for running on the host machine, e.g. in setting up `support` again

2018-10-16 14:32 UTC, richfitz commented on staging/scripts/destroy-disk
> +#!/usr/bin/env bash
This is meant to help with deleting disks without remembering or copying/pasting weird commands

2018-10-16 14:32 UTC, richfitz commented on staging/scripts/setup-start-on-boot
> +#!/usr/bin/env bash
see staging/scripts/start-on-boot.sh - mostly unchanged

2018-10-16 14:32 UTC, richfitz commented on staging/scripts/vault-prepare
> +set -e
This script is now made a little more robust with respect to where it is run from

2018-10-16 14:32 UTC, richfitz commented on staging/scripts/write-ssh-shortcuts
> +#!/usr/bin/env bash
For use on support for writing out the ssh shortcuts

2018-10-16 14:37 UTC, richfitz reviewed
comments explaining some bits added

2018-10-16 16:04 UTC, hillalex reviewed
Looks good, but lets talk through in person to make sure I understand what's going on with the provisioning logic

2018-10-16 16:04 UTC, hillalex commented on provision/setup-docker
> +    if [ -d $DOCKER_LARGE_DISK/docker/var-lib-docker ]; then
can use the `VAR_LIB_DOCKER` assigned on the previous line here

2018-10-16 16:04 UTC, hillalex commented on provision/setup-docker
> +        exit 0
Should we be exiting at this point? Don't we still have to make sure `/var/lib/docker` points to the right place and that docker is installed?

2018-10-17 09:18 UTC, richfitz commented on provision/setup-docker
> +        exit 0
yes!

2018-10-17 09:20 UTC, richfitz commented
Reminder for me: Depends on https://github.com/vimc/machine-metrics/pull/1/files and  https://github.com/vimc/montagu/pull/80 being merged, at which point the checkouts in the above can be removed

2018-10-17 10:20 UTC, hillalex requested changes
Couple of small things I noticed when running locally. Also are the steps to set up production documented anywhere?

2018-10-17 10:20 UTC, hillalex commented on provision/setup-vault
> +    echo "vault is already installed"
we could probably always run this, as it's pretty quick and means you always get the right version of vault installed?

2018-10-17 10:20 UTC, hillalex commented on provision/setup-montagu
> +    git clone --recursive https://github.com/vimc/montagu
need to specify $MONTAGU_PATH here

2018-10-17 11:17 UTC, richfitz commented
The only docs we have are the ones in `docs` itself - there's a `Production.md` file there but it could be expanded greatly!

2018-10-17 11:28 UTC, richfitz commented on provision/setup-vault
> +    echo "vault is already installed"
ok, the new version installs vault more enthusiastically now

2018-10-17 12:38 UTC, hillalex approved these changes

2018-10-17 12:38 UTC, merged