I2270 - update docs and diagram
vimc/montagu-machine pull request #3
Opened 2018-10-19 17:09 UTC by littledice

2018-10-19 17:09 UTC, littledice commented on docs/Annex.md
> +cd montagu-db-backup && ./start-metrics.sh
There is a ticket to make these come back up automatically:
https://vimc.myjetbrains.com/youtrack/issue/VIMC-2299

2018-10-22 09:30 UTC, richfitz approved these changes
I agree we're nearing (or have past) a sensible upper bound on complexity - raised https://vimc.myjetbrains.com/youtrack/issue/VIMC-2302

2018-10-25 09:04 UTC, richfitz requested changes

2018-10-25 09:04 UTC, richfitz commented on docs/Annex.md
>  docker start barman-montagu
can you remove the two barman-montagu lines - these are not needed now

2018-11-05 12:18 UTC, richfitz approved these changes

2018-11-05 13:07 UTC, merged